// <auto-generated />
using System;
using HeThongQuanLiBia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeThongQuanLiBia.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260527072152_AddTaiKhoanAuthentication")]
    partial class AddTaiKhoanAuthentication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeThongQuanLiBia.Models.Bans", b =>
                {
                    b.Property<int>("BanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BanId"));

                    b.Property<decimal>("GiaTheoGio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoaiBan")
                        .HasColumnType("int");

                    b.Property<string>("TenBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("BanId");

                    b.ToTable("Bans");
                });

            modelBuilder.Entity("HeThongQuanLiBia.Models.ChiTietDichVu", b =>
                {
                    b.Property<int>("ChiTietId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietId"));

                    b.Property<int>("DichVuId")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGiaTaiThoiDiemBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HoaDonId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("ChiTietId");

                    b.HasIndex("DichVuId");

                    b.HasIndex("HoaDonId");

                    b.ToTable("ChiTietDichVus");
                });

            modelBuilder.Entity("HeThongQuanLiBia.Models.DichVu", b =>
                {
                    b.Property<int>("DichVuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DichVuId"));

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoaiDichVu")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DichVuId");

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("HeThongQuanLiBia.Models.HoaDon", b =>
                {
                    b.Property<int>("HoaDonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoaDonId"));

                    b.Property<int>("BanId")
                        .HasColumnType("int");

                    b.Property<bool>("DaThanhToan")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GioRa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GioVao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienDichVu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienGio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("HoaDonId");

                    b.HasIndex("BanId");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("HeThongQuanLiBia.Models.TaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("TaiKhoans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "nv123",
                            Role = "NhanVien",
                            Username = "nhanvien"
                        });
                });

            modelBuilder.Entity("HeThongQuanLiBia.Models.ChiTietDichVu", b =>
                {
                    b.HasOne("HeThongQuanLiBia.Models.DichVu", "DichVu")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("DichVuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongQuanLiBia.Models.HoaDon", "HoaDon")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("HeThongQuanLiBia.Models.HoaDon", b =>
                {
                    b.HasOne("HeThongQuanLiBia.Models.Bans", "Ban")
                        .WithMany()
                        .HasForeignKey("BanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ban");
                });

            modelBuilder.Entity("HeThongQuanLiBia.Models.DichVu", b =>
                {
                    b.Navigation("ChiTietDichVus");
                });

            modelBuilder.Entity("HeThongQuanLiBia.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietDichVus");
                });
#pragma warning restore 612, 618
        }
    }
}
